import type { Metadata } from "next";
import { Geist_Mono, Figtree } from "next/font/google";
import { ThemeProvider } from "@/components/theme-provider";
import "./globals.css";

const figtTree = Figtree({
  variable: "--font-sans",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800", "900"],
});

const geistMono = Geist_Mono({
  variable: "--font-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${figtTree.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div className="min-h-screen flex">
            {/* Left sidebar */}
            <aside className="hidden lg:flex flex-1 px-6">Left Sidebar</aside>

            {/* Main content */}
            <main className="w-full max-w-4xl px-6 mx-auto">{children}</main>

            {/* Right sidebar */}
            <aside className="hidden lg:flex flex-1 px-6">Right Sidebar</aside>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
